package com.dnstechpack.dnscapes;

import com.dnstechpack.dnscapes.core.handler.TickHandler;
import com.dnstechpack.dnscapes.core.proxy.CommonProxy;
import com.dnstechpack.dnscapes.core.util.CapeHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;
import java.io.IOException;
import java.util.Arrays;

@Mod(modid="dnscapes", name="DNS Capes", version="1.0.1", dependencies="after:*")
public class DNSCapes
{

  @Mod.Instance("dnscapes")
  public DNSCapes instance;

  @SidedProxy(clientSide="com.dnstechpack.dnscapes.core.proxy.ClientProxy", serverSide="com.dnstechpack.dnscapes.core.proxy.CommonProxy")
  public static CommonProxy proxy;

  @Mod.EventHandler
  public void preInit(FMLPreInitializationEvent event)
    throws IOException
  {
    event.getModMetadata().authorList = Arrays.asList(new String[] { "MCWizard111", "Darkhax", "Madcock83" });
    event.getModMetadata().autogenerated = false;
    event.getModMetadata().credits = "Maintained by MCWizard111, Darkhax, Madcock83 and ShadowChild";
    event.getModMetadata().description = "This mod adds capes for DNS Team members and DNS Users";

    CapeHandler.init();

    TickRegistry.registerTickHandler(new TickHandler(), Side.CLIENT);
  }
}